"""AI Explanations — SHAP analysis with working Export Report."""
from __future__ import annotations
from datetime import datetime
import streamlit as st
from src.models.data_types import ExplanationBundle
from src.color_mapping import color_for_score, risk_label

ORGAN_ACCENT = {"heart": "#ef4444", "kidney": "#3b82f6", "liver": "#10b981"}
ORGAN_LABEL  = {
    "heart":  "Cardiovascular Risk Drivers",
    "kidney": "Renal Function Alteration",
    "liver":  "Hepatic Stress Indicators",
}


def _build_export_report(bundle: ExplanationBundle) -> str:
    """Build a plain-text AI Explanations export report."""
    now   = datetime.now().strftime("%d %B %Y, %H:%M")
    lines = []
    lines.append("=" * 60)
    lines.append("  MetaTwin-X — AI Explanations Report")
    lines.append(f"  Generated: {now}")
    lines.append("=" * 60)
    lines.append("")
    lines.append("SHAP (SHapley Additive exPlanations) analysis shows which")
    lines.append("biomarkers most influenced each organ's risk prediction.")
    lines.append("")

    for expl, organ_key in [
        (bundle.heart,  "Heart"),
        (bundle.kidney, "Kidney"),
        (bundle.liver,  "Liver"),
    ]:
        sc    = expl.predicted_score
        level = risk_label(sc)
        lines.append("-" * 60)
        lines.append(f"  {organ_key.upper()} — {sc*100:.1f}%  [{level} Risk]")
        lines.append("-" * 60)
        lines.append(f"  Base value (population average): {expl.base_value:.3f}")
        lines.append(f"  Predicted score:                 {sc:.3f}")
        lines.append(f"  SHAP contribution:               {sc - expl.base_value:+.3f}")
        lines.append("")
        lines.append("  Top 5 Features Influencing Score:")
        if expl.top_features:
            max_abs = max(abs(f.shap_value) for f in expl.top_features) or 1
            for i, feat in enumerate(expl.top_features[:5], 1):
                fname = feat.feature_name.replace("_", " ").title()
                sign  = "+" if feat.shap_value > 0 else ""
                pct   = abs(feat.shap_value) / max_abs * 100
                direction = "INCREASES risk" if feat.shap_value > 0 else "DECREASES risk"
                lines.append(f"  {i}. {fname:<30} {sign}{feat.shap_value:.4f}  ({pct:.0f}%)  — {direction}")
        lines.append("")
        if expl.sentences:
            lines.append("  Plain-Language Explanation:")
            for s in expl.sentences:
                lines.append(f"  • {s}")
        lines.append("")
        if expl.interaction_notes:
            lines.append("  Cross-Organ Interaction Adjustments:")
            for note in expl.interaction_notes:
                lines.append(f"  ⚡ {note}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("  DISCLAIMER")
    lines.append("=" * 60)
    lines.append("  This report is generated by an AI model for educational")
    lines.append("  purposes only. It does not constitute medical advice.")
    lines.append("  Always consult a qualified healthcare professional.")
    lines.append("=" * 60)
    return "\n".join(lines)


def render_explanations(bundle: ExplanationBundle):
    max_score = max(bundle.heart.predicted_score,
                    bundle.kidney.predicted_score,
                    bundle.liver.predicted_score)
    sev_pct   = int(max_score * 100)
    sev_color = "#dc2626" if sev_pct >= 70 else "#ea580c" if sev_pct >= 40 else "#16a34a"
    sev_label = "HIGH" if sev_pct >= 70 else "MODERATE" if sev_pct >= 40 else "LOW"

    # ── Page header ────────────────────────────────────────────────────
    st.markdown(f"""
<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;
            padding:18px 22px;margin-bottom:20px;
            box-shadow:0 1px 4px rgba(0,0,0,0.05);">
    <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;">
        <div>
            <div style="color:#0f172a;font-size:1rem;font-weight:800;
                        font-family:'Inter',sans-serif;margin-bottom:4px;">
                AI Explainability — SHAP Analysis
            </div>
            <div style="color:#64748b;font-size:0.78rem;font-family:'Inter',sans-serif;">
                Feature-level explanations showing which biomarkers drive each organ's risk score
            </div>
        </div>
        <span style="background:{'#fef2f2' if sev_pct>=70 else '#fff7ed' if sev_pct>=40 else '#f0fdf4'};
                     color:{sev_color};border:1px solid {'#fecaca' if sev_pct>=70 else '#fde68a' if sev_pct>=40 else '#bbf7d0'};
                     border-radius:8px;padding:5px 14px;font-size:0.75rem;font-weight:700;
                     font-family:'Inter',sans-serif;">
            Max Risk: {sev_pct}% — {sev_label}
        </span>
    </div>
</div>
""", unsafe_allow_html=True)

    # ── Export Report button ───────────────────────────────────────────
    report_text = _build_export_report(bundle)
    now_str     = datetime.now().strftime("%Y%m%d_%H%M")
    col1, col2, col3 = st.columns([1, 1, 2])
    with col1:
        st.download_button(
            label="⬇ Export AI Report",
            data=report_text.encode("utf-8"),
            file_name=f"metatwinx_ai_explanations_{now_str}.txt",
            mime="text/plain",
            use_container_width=True,
            key="export_ai_report",
        )
    with col2:
        if st.button("📊 View Dashboard", use_container_width=True, key="adj_params"):
            st.session_state["active_section"] = "home"
            st.rerun()

    st.markdown("<div style='height:12px;'></div>", unsafe_allow_html=True)

    # ── SHAP method note ───────────────────────────────────────────────
    st.markdown("""
<div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;
            padding:12px 16px;margin-bottom:18px;
            display:flex;align-items:flex-start;gap:10px;">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none"
         stroke="#0284c7" stroke-width="2" style="flex-shrink:0;margin-top:2px;">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
    </svg>
    <div style="color:#0369a1;font-size:0.8rem;line-height:1.6;font-family:'Inter',sans-serif;">
        <strong style="color:#0f172a;">SHAP values</strong> show how much each biomarker
        <span style="color:#dc2626;font-weight:600;">increases</span> or
        <span style="color:#2563eb;font-weight:600;">decreases</span>
        the predicted risk score relative to the population baseline.
        Longer bars = stronger influence.
    </div>
</div>
""", unsafe_allow_html=True)

    # ── Per-organ SHAP cards ───────────────────────────────────────────
    tab_h, tab_k, tab_l = st.tabs(["❤️ Heart", "🫘 Kidney", "🟤 Liver"])

    for tab, expl, organ_key in [
        (tab_h, bundle.heart,  "heart"),
        (tab_k, bundle.kidney, "kidney"),
        (tab_l, bundle.liver,  "liver"),
    ]:
        with tab:
            sc      = expl.predicted_score
            oc      = ORGAN_ACCENT[organ_key]
            sev_pct_o = int(sc * 100)
            sev_lbl   = "HIGH" if sev_pct_o >= 70 else "MODERATE" if sev_pct_o >= 40 else "LOW"
            sev_bg    = "#fef2f2" if sev_pct_o >= 70 else "#fff7ed" if sev_pct_o >= 40 else "#f0fdf4"
            sev_c     = "#dc2626" if sev_pct_o >= 70 else "#ea580c" if sev_pct_o >= 40 else "#16a34a"
            c         = color_for_score(sc)

            # Score bar
            st.markdown(f"""
<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:10px;
            padding:16px 20px;margin-bottom:16px;
            display:flex;align-items:center;gap:18px;">
    <div style="text-align:center;min-width:80px;">
        <div style="color:{c};font-size:2.2rem;font-weight:800;line-height:1;
                    font-family:'Inter',sans-serif;">
            {sc*100:.1f}<span style="font-size:0.85rem;font-weight:400;color:#94a3b8;">%</span>
        </div>
        <div style="color:#94a3b8;font-size:0.65rem;text-transform:uppercase;
                    letter-spacing:0.08em;margin-top:3px;font-family:'Inter',sans-serif;">
            Risk Score
        </div>
    </div>
    <div style="width:1px;height:52px;background:#e2e8f0;"></div>
    <div style="flex:1;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
            <div style="color:#0f172a;font-size:0.86rem;font-weight:700;
                        font-family:'Inter',sans-serif;">{ORGAN_LABEL[organ_key]}</div>
            <span style="background:{sev_bg};color:{sev_c};border-radius:20px;
                         padding:3px 12px;font-size:0.68rem;font-weight:700;
                         font-family:'Inter',sans-serif;">{sev_pct_o}% {sev_lbl}</span>
        </div>
        <div style="height:6px;background:#f1f5f9;border-radius:3px;overflow:hidden;">
            <div style="height:100%;width:{sc*100:.1f}%;
                        background:linear-gradient(90deg,{oc}66,{c});border-radius:3px;"></div>
        </div>
        <div style="color:#94a3b8;font-size:0.7rem;margin-top:6px;font-family:'Inter',sans-serif;">
            Base: {expl.base_value:.3f} &nbsp;·&nbsp; SHAP contribution: {sc - expl.base_value:+.3f}
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

            # SHAP feature bars
            if expl.top_features:
                st.markdown("""
<div style="color:#94a3b8;font-size:0.65rem;font-weight:700;text-transform:uppercase;
            letter-spacing:0.1em;margin-bottom:12px;font-family:'Inter',sans-serif;">
    Top 5 Features Influencing Score
</div>
""", unsafe_allow_html=True)
                max_abs = max(abs(f.shap_value) for f in expl.top_features) or 1
                for feat in expl.top_features[:5]:
                    fname  = feat.feature_name.replace("_", " ").title()
                    val    = feat.shap_value
                    pct    = abs(val) / max_abs * 100
                    bar_c  = "#ef4444" if val > 0 else "#2563eb"
                    val_c  = "#dc2626" if val > 0 else "#2563eb"
                    sign   = f"+{val:.3f}" if val > 0 else f"{val:.3f}"
                    direction = "↑ Increases risk" if val > 0 else "↓ Decreases risk"
                    st.markdown(
                        f'<div style="margin-bottom:12px;">'
                        f'<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:5px;">'
                        f'<span style="color:#374151;font-size:0.82rem;font-family:Inter,sans-serif;">{fname}</span>'
                        f'<div style="display:flex;align-items:center;gap:10px;">'
                        f'<span style="color:#94a3b8;font-size:0.7rem;font-family:Inter,sans-serif;">{direction}</span>'
                        f'<span style="color:{val_c};font-size:0.84rem;font-weight:700;font-family:Inter,sans-serif;">{sign}</span>'
                        f'</div></div>'
                        f'<div style="height:8px;background:#f1f5f9;border-radius:4px;overflow:hidden;">'
                        f'<div style="height:100%;width:{pct:.0f}%;background:{bar_c};border-radius:4px;"></div>'
                        f'</div>'
                        f'</div>',
                        unsafe_allow_html=True,
                    )

            # Plain-language sentences
            if expl.sentences:
                st.markdown("""
<div style="color:#94a3b8;font-size:0.65rem;font-weight:700;text-transform:uppercase;
            letter-spacing:0.1em;margin:14px 0 8px;font-family:'Inter',sans-serif;">
    Plain-Language Explanation
</div>
""", unsafe_allow_html=True)
                for s in expl.sentences:
                    is_inc = "increased" in s.lower()
                    bg_c   = "#fef2f2" if is_inc else "#eff6ff"
                    dot_c  = "#ef4444" if is_inc else "#2563eb"
                    st.markdown(
                        f'<div style="background:{bg_c};border-radius:8px;padding:10px 14px;'
                        f'margin-bottom:8px;display:flex;gap:10px;align-items:flex-start;">'
                        f'<span style="width:6px;height:6px;border-radius:50%;background:{dot_c};'
                        f'flex-shrink:0;margin-top:6px;display:inline-block;"></span>'
                        f'<span style="color:#374151;font-size:0.8rem;line-height:1.6;'
                        f'font-family:Inter,sans-serif;">{s}</span>'
                        f'</div>',
                        unsafe_allow_html=True,
                    )

            # Cross-organ interaction notes
            if expl.interaction_notes:
                st.markdown("""
<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;
            padding:12px 16px;margin-top:12px;">
    <div style="color:#92400e;font-size:0.75rem;font-weight:700;margin-bottom:8px;
                font-family:'Inter',sans-serif;">⚡ Cross-Organ Interaction Adjustments</div>
""", unsafe_allow_html=True)
                for note in expl.interaction_notes:
                    st.markdown(
                        f'<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;'
                        f'padding:8px 14px;margin-bottom:6px;font-size:0.74rem;color:#78350f;'
                        f'font-family:Inter,sans-serif;">⚡ {note}</div>',
                        unsafe_allow_html=True,
                    )
