"""Recommendations — with working Generate Full Care Plan export."""
from __future__ import annotations
from datetime import datetime
import streamlit as st
from src.models.data_types import RecommendationList

CAT_CONFIG = {
    "clinical_consultation": {
        "label": "CLINICAL",  "bg": "#fef2f2", "fg": "#dc2626",
        "border": "#ef4444",  "priority": "PRIORITY 1",
        "p_bg": "#fef2f2",    "p_fg": "#dc2626",
    },
    "lifestyle_habit": {
        "label": "LIFESTYLE", "bg": "#f0fdf4", "fg": "#16a34a",
        "border": "#22c55e",  "priority": "PRIORITY 2",
        "p_bg": "#f0fdf4",    "p_fg": "#16a34a",
    },
    "dietary_modification": {
        "label": "DIETARY",   "bg": "#eff6ff", "fg": "#2563eb",
        "border": "#3b82f6",  "priority": "PRIORITY 2",
        "p_bg": "#eff6ff",    "p_fg": "#2563eb",
    },
    "physical_activity": {
        "label": "EXERCISE",  "bg": "#faf5ff", "fg": "#7c3aed",
        "border": "#8b5cf6",  "priority": "PRIORITY 3",
        "p_bg": "#faf5ff",    "p_fg": "#7c3aed",
    },
}

ORGAN_COLOR = {
    "heart": "#ef4444", "kidney": "#3b82f6",
    "liver": "#10b981", "general": "#7c3aed",
}


def _build_care_plan(rec_list: RecommendationList) -> str:
    """Build a complete downloadable care plan document."""
    now   = datetime.now().strftime("%d %B %Y, %H:%M")
    items = rec_list.items
    lines = []

    lines.append("=" * 65)
    lines.append("  MetaTwin-X — Personalised Full Care Plan")
    lines.append(f"  Generated: {now}")
    lines.append("=" * 65)
    lines.append("")
    lines.append("This care plan is generated by the MetaTwin-X AI system based")
    lines.append("on your multi-organ risk assessment. It is prioritised by")
    lines.append("clinical urgency and projected health impact.")
    lines.append("")

    # Group by category
    categories = {
        "clinical_consultation": "SECTION 1: CLINICAL CONSULTATIONS (Urgent)",
        "physical_activity":     "SECTION 2: PHYSICAL ACTIVITY PROTOCOL",
        "dietary_modification":  "SECTION 3: DIETARY MODIFICATIONS",
        "lifestyle_habit":       "SECTION 4: LIFESTYLE INTERVENTIONS",
    }

    for cat_key, section_title in categories.items():
        cat_items = [r for r in items if r.category == cat_key]
        if not cat_items:
            continue
        lines.append("-" * 65)
        lines.append(f"  {section_title}")
        lines.append("-" * 65)
        for i, rec in enumerate(cat_items, 1):
            organ = rec.organ.upper()
            priority_pct = int(rec.priority * 100)
            lines.append(f"  [{i}] [{organ}] Priority: {priority_pct}%")
            # Word-wrap the recommendation text at 60 chars
            words = rec.text.split()
            line_buf, wrapped = [], []
            for w in words:
                if len(" ".join(line_buf + [w])) > 58:
                    wrapped.append("      " + " ".join(line_buf))
                    line_buf = [w]
                else:
                    line_buf.append(w)
            if line_buf:
                wrapped.append("      " + " ".join(line_buf))
            lines.extend(wrapped)
            lines.append("")

    # Summary stats
    clinical_count  = sum(1 for r in items if r.category == "clinical_consultation")
    high_priority   = sum(1 for r in items if r.priority >= 0.6)
    lines.append("=" * 65)
    lines.append("  CARE PLAN SUMMARY")
    lines.append("=" * 65)
    lines.append(f"  Total recommendations:      {len(items)}")
    lines.append(f"  Clinical consultations:     {clinical_count}")
    lines.append(f"  High-priority actions:      {high_priority}")
    lines.append(f"  Preventive actions:         {len(items) - high_priority}")
    lines.append("")
    lines.append("  IMPLEMENTATION TIMELINE")
    lines.append("  ─────────────────────────────────────────────────────────")
    lines.append("  Immediate (0–2 weeks):  Complete all clinical consultations")
    lines.append("  Short-term (1–3 months): Establish exercise and diet routines")
    lines.append("  Long-term (3–12 months): Monitor progress, adjust protocols")
    lines.append("")
    lines.append("=" * 65)
    lines.append("  DISCLAIMER")
    lines.append("=" * 65)
    lines.append("  This care plan is for educational purposes only and does")
    lines.append("  not constitute medical advice, diagnosis, or treatment.")
    lines.append("  Always consult a qualified healthcare professional before")
    lines.append("  making changes to your health regimen.")
    lines.append("=" * 65)
    return "\n".join(lines)


def _rec_title(text: str) -> str:
    words = text.split()
    if len(words) <= 5:
        return text
    title_words = []
    for w in words[:6]:
        title_words.append(w)
        if len(" ".join(title_words)) > 32:
            break
    return " ".join(title_words)


def render_recommendations(rec_list: RecommendationList):
    items    = rec_list.items
    clinical = [r for r in items if r.category == "clinical_consultation"]
    n_recs   = len(items)
    urgent   = sum(1 for r in items if r.priority >= 0.6)

    # ── Header ─────────────────────────────────────────────────────────
    st.markdown(f"""
<div style="background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;
            padding:18px 22px;margin-bottom:20px;
            box-shadow:0 1px 4px rgba(0,0,0,0.05);">
    <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;">
        <div>
            <div style="color:#0f172a;font-size:1rem;font-weight:800;
                        font-family:'Inter',sans-serif;margin-bottom:4px;">
                Clinical Recommendations
            </div>
            <div style="color:#64748b;font-size:0.78rem;font-family:'Inter',sans-serif;">
                {n_recs} recommendations · {len(clinical)} clinical consultations ·
                {urgent} high-priority actions
            </div>
        </div>
        <div style="display:flex;gap:8px;flex-wrap:wrap;">
            <span style="background:#fee2e2;color:#dc2626;border-radius:8px;
                         padding:5px 12px;font-size:0.72rem;font-weight:700;
                         font-family:'Inter',sans-serif;">
                {len(clinical)} Urgent Consults
            </span>
            <span style="background:#dbeafe;color:#1d4ed8;border-radius:8px;
                         padding:5px 12px;font-size:0.72rem;font-weight:700;
                         font-family:'Inter',sans-serif;">
                {n_recs} Total Actions
            </span>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

    # ── Generate Full Care Plan button ─────────────────────────────────
    care_plan_text = _build_care_plan(rec_list)
    now_str        = datetime.now().strftime("%Y%m%d_%H%M")

    dl_col, info_col = st.columns([1, 2])
    with dl_col:
        st.download_button(
            label="📋 Download Full Care Plan",
            data=care_plan_text.encode("utf-8"),
            file_name=f"metatwinx_care_plan_{now_str}.txt",
            mime="text/plain",
            use_container_width=True,
            type="primary",
            key="download_care_plan",
        )
    with info_col:
        st.markdown("""
<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;
            padding:10px 14px;font-size:0.78rem;color:#166534;
            font-family:'Inter',sans-serif;line-height:1.5;">
    ✅ Your personalised care plan includes all recommendations grouped by
    category with implementation timeline. Download as a text file to share
    with your healthcare provider.
</div>
""", unsafe_allow_html=True)

    st.markdown("<div style='height:16px;'></div>", unsafe_allow_html=True)

    # ── Recommendation cards ───────────────────────────────────────────
    for rec in items[:10]:
        cfg    = CAT_CONFIG.get(rec.category, CAT_CONFIG["lifestyle_habit"])
        oc     = ORGAN_COLOR.get(rec.organ, "#64748b")
        impact = int(rec.priority * 100)

        if rec.category == "clinical_consultation":
            impact_text = f"Projected impact: -{impact}% organ risk over 90 days"
        elif rec.category == "physical_activity":
            impact_text = f"Projected impact: -{impact//2}% systolic BP modifier"
        elif rec.category == "dietary_modification":
            impact_text = f"Projected impact: -{impact//3}% multi-organ stress"
        else:
            impact_text = f"Projected impact: -{impact//4}% systemic inflammation"

        st.markdown(
            f'<div style="background:#ffffff;border-radius:10px;padding:16px 18px;'
            f'margin-bottom:10px;box-shadow:0 1px 6px rgba(0,0,0,0.05);'
            f'border-left:4px solid {cfg["border"]};">'
            f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap;">'
            f'<span style="background:{cfg["bg"]};color:{cfg["fg"]};font-size:0.65rem;'
            f'font-weight:700;padding:3px 8px;border-radius:4px;text-transform:uppercase;'
            f'font-family:Inter,sans-serif;">{cfg["label"]}</span>'
            f'<span style="background:{cfg["p_bg"]};color:{cfg["p_fg"]};font-size:0.65rem;'
            f'font-weight:700;padding:3px 8px;border-radius:4px;font-family:Inter,sans-serif;">'
            f'{cfg["priority"]}</span>'
            f'<span style="background:{oc}14;color:{oc};font-size:0.65rem;font-weight:600;'
            f'padding:3px 8px;border-radius:4px;font-family:Inter,sans-serif;">'
            f'{rec.organ.capitalize()}</span>'
            f'<span style="margin-left:auto;color:#94a3b8;font-size:0.68rem;'
            f'font-family:Inter,sans-serif;">Priority: {impact}%</span>'
            f'</div>'
            f'<div style="color:#0f172a;font-size:0.86rem;font-weight:700;margin-bottom:6px;'
            f'font-family:Inter,sans-serif;">{_rec_title(rec.text)}</div>'
            f'<div style="color:#374151;font-size:0.8rem;line-height:1.6;'
            f'font-family:Inter,sans-serif;">{rec.text}</div>'
            f'<div style="color:#94a3b8;font-size:0.72rem;margin-top:8px;'
            f'font-family:Inter,sans-serif;">📈 {impact_text}</div>'
            f'</div>',
            unsafe_allow_html=True,
        )

    # ── Disclaimer ─────────────────────────────────────────────────────
    st.markdown("""
<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;
            padding:12px 16px;margin-top:8px;
            display:flex;align-items:flex-start;gap:10px;">
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
         stroke="#d97706" stroke-width="2" style="flex-shrink:0;margin-top:2px;">
        <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
        <line x1="12" y1="9" x2="12" y2="13"/>
        <line x1="12" y1="17" x2="12.01" y2="17"/>
    </svg>
    <div style="font-size:0.74rem;color:#78350f;line-height:1.5;font-family:'Inter',sans-serif;">
        <strong>Medical Disclaimer:</strong> These recommendations are for educational purposes
        only and do not constitute medical advice. Always consult a qualified healthcare
        professional before making changes to your health regimen.
    </div>
</div>
""", unsafe_allow_html=True)
